# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release Branch Delete Latest release


on:
  workflow_dispatch:

jobs:
  delete:
    runs-on: Windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        repo:
        keep_latest: 0
        delete_tag_pattern: Latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: dev-drprasad/delete-tag-and-release@v0.2.0
      with:
          delete_release: true # default: false
          tag_name: Latest # tag name to delete
          repo:  # target repo (optional). defaults to repo running this action
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
